<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class PenggunaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pengguna')->insert([
            [
                'id_pengguna'   => 1,
                'nama_lengkap'  => 'Komandan Utama',
                'username'      => 'komandan',
                'email'         => 'komandan@siap.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'komandan',
                'jenis_jadwal'  => 'non_shift',
                'tanggal_lahir' => '1980-05-15',
                'no_hp'         => '081234567890',
                'alamat'        => 'Jln. Merdeka No. 1, Jakarta',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/komandan.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 2,
                'nama_lengkap'  => 'Anggota Jaga Satu',
                'username'      => 'anggota1',
                'email'         => 'anggota1@siap.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1995-02-20',
                'no_hp'         => '081211112222',
                'alamat'        => 'Jln. Gatot Subroto No. 10, Jakarta',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/anggota.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 3,
                'nama_lengkap'  => 'Admin BAU',
                'username'      => 'bau',
                'email'         => 'admin_bau@siap.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'bau',
                'jenis_jadwal'  => null,
                'tanggal_lahir' => '1990-11-30',
                'no_hp'         => '081233334444',
                'alamat'        => 'Jln. Sudirman No. 12, Jakarta',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/bau.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            // Data dari Excel - Personil Security STIS
            [
                'id_pengguna'   => 4,
                'nama_lengkap'  => 'BUDIONO',
                'username'      => 'budiono',
                'email'         => 'budiandromeda0479@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'komandan',
                'jenis_jadwal'  => 'non_shift',
                'tanggal_lahir' => '1979-04-13',
                'no_hp'         => '081228945175',
                'alamat'        => 'Jln. Otista Raya No. 64c Bidara cina, Jatinegara, Jakarta Timur',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/budiono.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 5,
                'nama_lengkap'  => 'ANDI SABRINA AULIA',
                'username'      => 'andi_sabrina',
                'email'         => 'andisabrinaaulia@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'non_shift',
                'tanggal_lahir' => '1999-07-02',
                'no_hp'         => '081388726991',
                'alamat'        => 'Jln. H. Inen Rt.003 / Rw.024 Lubang Buaya Cipayung, Jakarta Timur',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/andi_sabrina.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 6,
                'nama_lengkap'  => 'ARDI KURNIADI',
                'username'      => 'ardi_kurniadi',
                'email'         => 'ardikurniadi55@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'non_shift',
                'tanggal_lahir' => '1988-10-14',
                'no_hp'         => '087888224534',
                'alamat'        => 'Ciwaringin Tanah Sewa Rt.01 Rw. 02 Cibogor, Bogor, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/ardi_kurniadi.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 7,
                'nama_lengkap'  => 'MAULANA YUSUP',
                'username'      => 'maulana_yusup',
                'email'         => 'Maulanaayusup98@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1998-06-12',
                'no_hp'         => '083148118482',
                'alamat'        => 'Jl. Tamansari X No.15 Tamansari, Jakarta Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/maulana_yusup.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 8,
                'nama_lengkap'  => 'RIZKY SUHARYOKO',
                'username'      => 'rizky_suharyoko',
                'email'         => 'komenggibedmutz@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1989-12-23',
                'no_hp'         => '085778683213',
                'alamat'        => 'Kp. Rawa Pasung Rt.001 Rw.001 Kotabaru, Bekasi Barat, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/rizky_suharyoko.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 9,
                'nama_lengkap'  => 'MUHAMMAD KARIM',
                'username'      => 'muhammad_karim',
                'email'         => 'mk9435795@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'non_shift',
                'tanggal_lahir' => '1983-03-05',
                'no_hp'         => '087883946291',
                'alamat'        => 'Jl. Batu No. 32 C Rt.013 Rw.009 Srengseng Sawah, Jagakarsa, Jakarta Selatan',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/muhammad_karim.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 10,
                'nama_lengkap'  => 'FAISHAL ROMZI',
                'username'      => 'faishal_romzi',
                'email'         => 'faishalromzi61@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1998-06-03',
                'no_hp'         => '081540331584',
                'alamat'        => 'Jln. Bintara 8 Rt.002 / Rw.003 No. 184i, Bekasi Barat, Bekasi, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/faishal_romzi.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 11,
                'nama_lengkap'  => 'JULIAN ROMAN BARUS',
                'username'      => 'julian_roman',
                'email'         => 'romanjulian340@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1993-07-16',
                'no_hp'         => '081219777606',
                'alamat'        => 'Muara Kidul Rt. 004 / Rw.011 Pasir Jaya Bogor Barat, Kota Bogor, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/julian_roman.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 12,
                'nama_lengkap'  => 'MUHAMAD SONY MUSTOPO',
                'username'      => 'sony_mustopo',
                'email'         => 'muhammadsonymustopo@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1993-05-02',
                'no_hp'         => '081297786662',
                'alamat'        => 'Jln. Kayu Manis Raya5 at siri permai Rt. 009 Rw. 012 desa Ragajaya Bojong Gede Bogor, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/sony_mustopo.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id_pengguna'   => 13,
                'nama_lengkap'  => 'MUHAMAD RIZKI',
                'username'      => 'muhamad_rizki',
                'email'         => 'muhd.rzki96@gmail.com',
                'password'      => Hash::make('password123'),
                'peran'         => 'anggota',
                'jenis_jadwal'  => 'shift',
                'tanggal_lahir' => '1996-06-04',
                'no_hp'         => '085718838452',
                'alamat'        => 'Jln. Saadih 2 No.16 Taman Induk Rt.002 Rw.011 Kel. Cipayung Cipayung Bogor, Jawa Barat',
                'status'        => 'Aktif',
                'foto_profil'   => 'akun/muhamad_rizki.jpg',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
        ]);
    }
}
